[package]
name = "desksweep"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.37"
dircpy = "0.3.16"
directories = "5.0.1"
eframe = "0.27.2"
rfd = "0.14.1"
